name: jolly_podcast
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.5.0
  stacked_services: ^1.6.0
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  json_annotation: ^4.9.0
  reactive_forms: ^18.2.0
  shared_preferences: ^2.5.3
  retrofit: ^4.9.1
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.6.1
  stacked_generator: ^2.0.0
  retrofit_generator: ^10.2.0
  json_serializable: ^6.11.3
  freezed: ^3.2.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/pngs/
    - assets/svgs/

  fonts:
    - family: nunito
      fonts:
        - asset: fonts/Inter-Thin.ttf
          weight: 300
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700